- files/cgroup.conf
- tasks/common.yml
Added a cgroup.conf file, without it task/cgroup does nothing.
Restraining memory needs to be tested with centos7, on centos6 it did not work properly.
Currently only restrains cpus.
> Added cgroup support for cpusets

- defaults/main.yml
- tasks/common.yml
- tasks/service.yml
Make sure that the primary group of the slurm user is the slurm group. And lets set the homedir to /, that's the usual RHEL convention for daemon users that don't have their own home.
> Slurm uidgid2

- templates/slurmdbd.conf.j2
slurmd's and slurmctld already log via syslog, which is the right thing to do (TM). So lets do it for slurmdbd as well.
> Make slurmdbd log via syslog

- defaults/main.yml
This should reduce fragmentation when running a mixed workload of parallel and serial jobs.
> Pack serial jobs at end by default

- templates/slurm.conf.j2
ControlAddr is useful in case it's a different hostname than the short
name defined in ControlMachine. We need it because our service nodes
have have the same short names on both the external and internal
interface, and by default the login node tries to connect to the
control machine over the external interface which doesn't work due to
the firewall.
> Allow setting ControlAddr

- tasks/compute.yml
When installing a new node, ansible-pull-script fails if the node is
not present in slurm.conf, preventing the playbook from
continuing. OTOH, putting the new nodes into slurm.conf before
verifying the they have installed correctly might not be wise either.
Further, set state=started for slurmd instead of restarted, this
prevents bouncing slurmd unnecessarily every time ansible runs.
> Ignore errors when starting slurmd, and set state=started

- OPENSTACK.md
- README.md
- defaults/main.yml
- tasks/main.yml
- tests/test.yml
slurm_type is redundant since the "slurm type" is already given by the slurm_compute and slurm_service host groups in the ansible hosts file (those groups are defined in fgci-ansible:/examples/hosts-example so all sites should have them).
This patch also gets rid of the slurm type "submit"; now all nodes that this role is run against become "submit nodes" (i.e. they run munged, and slurm command line tools are available).
> Remove slurm_type

- meta/main.yml
- tasks/dbd.yml
also:
- assert was in the middle of the dbd.yml, but it at the top
- made the "create slurm sql user with password and privs" task also
run if mysqlslurmuser task changed (meaning it was just created by
the "create slurm sql user" task
- update the slurm_mysql_password set to always update the password if
it differs
- some task naming changes to be more accurate
> create the slurm mysql_user with a password

- tasks/dbd.yml
- tasks/service.yml
- so that they are done after munge.key generation
- github issue #57 
- while testing on a setup where the accounting host and the slurmctld are on the same it skips these two tasks. Would be nice if this could also be tested on a setup where they are different before we merge.
> move the munge tasks for dbd host to service.yml

- templates/slurm_rsyslog.conf
Also, check that the program name starts with slurm, this avoid having
pam_slurm messages in the slurm.log (they belong in the
auth.log/secure/etc.).
Finally, stop processing after this so slurm messages don't get
replicated in other log files.
> Use the modern standard rsyslog format

- README.md
- tasks/dbd.yml
- tasks/main.yml
- tasks/upgrade.yml
- tasks/version.yml
- templates/dump-all-databases.sh.j2
With this update the slurm role will pause ( only ) on the slurmdbd host if the slurm version in 
<pre>
yum list installed slurm | grep slurm | awk '{print $2}' | cut -d'-' -f1|cut -d "." -f1-2|sed -e 's/\.//'
</pre>
and 
<pre>
{{ fgci_slurmrepo_version | replace('fgcislurm', '')}}
</pre>
are different (and if the first is not an empty string)
Some comments on this would be nice. What do you think @jabl  and @A1ve5 ?
Should we add notes in ansible for where users should look for documentation? FGI/FGCI confluence is not ideal as that's behind HAKA authentication
I mentioned in #63 that the cgroup variable default has changed. Fortunately we have already the new default set in this role, so we don't need to make SLURM version dependent variable files.
> Slurm upgrade 16.08

- templates/slurm_rsyslog.conf
Otherwise, stopping here prevents sending the log message to a central
log server.
> Don't stop processing message after outputting to local slurm log.

- defaults/main.yml
- tasks/dbd.yml
- templates/.my.cnf.j2
Configure a mysql root user.
It is possible to disable it by setting a variable: slurm_manage_mysql_security to False
I would like another eye on this before merging and testing in our test cluster.
Based on travis testing it seems to work when installing from scratch, maybe there are some caveats for when doing it on a running system?
> Root db access

- defaults/main.yml
- tasks/service.yml
slurmd_tmp_dir was created, but never used for anything.
> Remove unused variables slurm_tmp_dir, slurmd_tmp_dir

- defaults/main.yml
- templates/slurm.conf.j2
The seff script is a simple script which checks the CPU and memory
usage vs. allocated. smail is a small wrapper around /bin/mail which
adds the seff output to the body of the notification emails that slurm
sends (by default the body is empty). Both scripts are part of the
slurm-seff package.
See https://bugs.schedmd.com/show_bug.cgi?id=1611
> Send a slurm efficiency report if the user requests mail notification

- README.md
- defaults/main.yml
- tasks/main.yml
- tasks/service.yml
- tasks/slurmctld.yml
- templates/slurm.conf.j2
This PR takes the changes from #75 and instead:
- dbd.yml is again before service.yml (is there a reason why you moved it after service.yml?)
- the sacctmgr "create cluster" command is after slurmctld is started in slurmctld.yml
Summary of changes:
- new variables: {{ slurm_backup_controller }} and {{ slurm_backup_addr }} which are undefined by default.
- some tasks moved out of service.yml into slurmctld.yml
> Allow running a backup slurmctld - attempt 2

- tasks/slurmctld.yml
Do some raw shell string mangling instead of the jinja2 magic ansible is unhappy with.
Basically looks for the sitename in the output and changes it to FOUND, which ansible then happily should parse.
As buggy as the previous version. Don't try naming your cluster "1" or "normal"
> This should fix issue #83

- .travis.yml
- README.md
- defaults/main.yml
- tasks/common.yml
- tasks/compute.yml
- tasks/service.yml
- tasks/slurmctld.yml
- tests/fgcislurm1508
- tests/fgcislurm1605/Dockerfile
- tests/fgcislurm1702
- tests/test-in-docker-image.sh
- tests/test1508.yml
- tests/test1605.yml
- tests/test1702.yml
Attempt 1 at a PR to support SLURM 17.02.
Comments in regards to the backwards compatibility with SLURM 16.05?
---
This role no longer works with a SLURM earlire than 17.02 as of this
commit.
- install slurm-contribs instead of slurm-sjstat,sjobexit,seff
- no longer install slurm-slurmdb-direct
- no longer disable slurm initd script
- change fgci_slurmrepo_version default from pointing to yum repo
with 15.08 to one with 17.02
> support for SLURM 17.02 - #77

- defaults/main.yml
- templates/slurm_logrotate.j2
https://slurm.schedmd.com/SLUG17/Roadmap.pdf says to use SIGUSR2 instead
of HUP. This only works with SLURM 17.11. 
HUP runs a reconfigure which can cause performance issues.
Additionally, before this commit the kill command was:
<pre>
/bin/kill -HUP cat /var/run/slurmctld.pid 2>/dev/null 2> /dev/null || true
</pre>
Running that command directly does not seem to work (and errors are hidden by the stdout/stderr redirections):
<pre>
kill: cannot find process "cat"
kill: cannot find process "/var/run/slurmctld.pid"
</pre>
So put the cat inside a $()
> kill -SIGUSR2 for logrotate

- defaults/main.yml
In the slurm.conf(5) man page it is recommended to use the
task/affinity plugin to set affinity and not use the task affinity
feature of the task/cgroup plugin. This makes the defaults match this
recommendation.
> Set task affinity per SchedMD recommendation

- README.md
- defaults/main.yml
- templates/slurm.conf.j2
- templates/slurmdbd.conf.j2
- vars/slurm_1508.yml
- vars/slurm_1605.yml
- vars/slurm_1702.yml
- vars/slurm_1711.yml
- vars/slurm_default.yml
With this PR this ansible-role now supports setting vars by default in slurmdbd.conf and slurm.conf for some SLURM versions.
Already before a user of this role could set ansible variable {{ slurm_ExtraParamsList }} and it would add those to slurm.conf
Together with the above changes we with SLURM 17.11 (only) now set slurmdbd, slurmctld and slurmd syslog levels to "info" rather than the default "quiet" or "fatal".
The reason why the settings are not added into slurm.conf is because slurm does not start with unknown parameters in slurm.conf - it would have broken backwards compatibility with versions prior to 17.11.
Some background information: https://bugs.schedmd.com/show_bug.cgi?id=4514
> Support for SLURM version specific settings in slurm and slurmdbd.conf

- defaults/main.yml
- templates/cgroup.conf.j2
- vars/slurm_1702.yml
- vars/slurm_1711.yml
Setting ConstrainKmemSpace=no works around a bug in the Linux kernel
that manifests itself as slurm failing to create a memory cgroup, with
an error message like
slurmstepd: error: task/cgroup: unable to add task[pid=1234] to memory cg '(null)'
See slurm bug 5082.
> Set ConstrainKmemSpace=no by default

- UPGRADE.md
- defaults/main.yml
- tasks/common.yml
- tasks/common_ubuntu.yml
- tasks/redhat.yml
- vars/slurm_ohpc.yml
Allow using slurm packages from the OpenHPC repository instead of from
the FGCI one.  In order to avoid inadvertent upgrade the package
version are locked using the yum versionlock plugin. Upgrade
instructions are provided in UPGRADE.md.
> Allow using OpenHPC slurm packages

- tasks/common.yml
- tasks/common_ubuntu.yml
- tasks/compute.yml
- tasks/compute_ubuntu.yml
- tasks/dbd.yml
- tasks/service.yml
- tasks/slurmctld.yml
Instead of looping with a with_items construct, these ansible commands
can take a list directly which is more efficient than invoking yum/apt
separately for each item.
> Provide package lists directly to package/apt commands

- .travis.yml
- Trusty has been deprecated, use the default (xenial at the moment).
- sudo is always available as the travis container-based
infrastructure has been deprecated.
- group tag isn't necessary anymore either.
- Use language: generic as we're using docker for everything and not
python.
> Modernize travis settings

- tasks/compute_ubuntu.yml
The current version of compute_ubuntu.yml does not generate cgroup_allowed_devices_file.conf. The missing configuration file causes startup errors for slurm.
This pull request fixes that.
> tasks/compute_ubuntu.yml: Added cgroup_allowed_devices_file.conf generation

- UPGRADE.md
When updating slurmdbd, before starting slurmdbd to do the DB upgrade,
make sure munge is running. The DB upgrade will be done regardless,
but if munge isn't running slurmdbd will generate errors after the
upgrade is done.
> Make sure munge is started before starting slurmdbd

- templates/slurm.conf.j2
In the vars/ files we install the mailx package, which provides
/bin/mail, which is also the default setting of MailProg if it's not
present in slurm.conf. OTOH the current setting of /usr/bin/smail
generates an error because that binary is not provided by mailx. Hence
just remove this setting and use the default.
> Remove incorrect setting of MailProg

- vars/slurm_ohpc.yml
Remove slurm-libpmi-ohpc and slurm-ohpc-fgci-addons from
slurm_service_packages and slurm_compute_packages since they are
already in the slurm_packages list which gets installed everywhere.
> Cleanup package lists for ohpc

- meta/main.yml
Galaxy doesn't like the way we say ansible-role-pam is a dependency:
<pre>
Starting import: task_id=525198, repository=CSCfi/ansible-role-slurm 
===== LOADING ROLE ===== 
Task "525198" failed: Expecting dependency name format to match "username.role_name", got ansible-role-pam 
</pre>
This PR tries out a new syntax where we specify the role-pam used in fgci-ansible: https://github.com/CSCfi/fgci-ansible/blob/master/requirements.yml#L178
It does not specify a version, but it is possible to also do that: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#dependencies
Is this dependency listing in meta/main.yml even needed anymore? We haven't listed the NHC role in there but it's in the requirements.yml.
> Hello Ansible Galaxy

- README.md
- defaults/main.yml
- tasks/common.yml
- tasks/common_ubuntu.yml
- tasks/service.yml
Allow creations of local slurm user with given uid/gid. Needed if there is no common auth-server in use at installation time (including when creating e.g. ohpc images).
> option to set uig/gid manually

- tasks/common.yml
x11.conf not removed from /etc/slurm/plugstack.conf.d even if x11 spank plugin is turned off. Both conditions should be enough alone to remove plugin configuration.
> x11 spank plugin is not correctly turned off

- vars/slurm_ohpc.yml
Minor cleanup to support newer slurm versions than 18.08.
> Deprecate old slurm-ohpc-server metapackage

- templates/namespace_clean.sh.j2
When multiple users have jobs on a single node, the epilog script fails. Adding quotation marks fixes this.
Witnessed on triton.
> Add quotation marks to epilog script (templates/namespace_clean.sh.j2)
